version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: models-web
    volumes:
      - .:/code
    #command: pip install django==3.1.14|grep pip
     # these commands below do not work
#    command: cp -r /usr/local/lib/python3.8/site-packages/django/contrib/admin /code/staticfiles/
#    command: cp -r /usr/local/lib/python3.8/site-packages/django/contrib/admin /app/staticfiles/

#    command: /app/manage.py makemigrations
#    command: /code/manage.py makemigrations

#    command: /app/manage.py migrate
#    command: /code/manage.py migrate

#    command: /app/manage.py collectstatic
#    command: /code/manage.py collectstatic

#    command: python3 manage.py migrate
#    command: python3 manage.py collectstatic


#     command: /app/manage.py collectstatic
#    command: /code/manage.py collectstatic
#    command: python3 manage.py migrate
#    command: /app/expect
    #command: find /app
    command: python /code/manage.py runserver 0.0.0.0:8000 #  use docker logs -f to tail
    ports:
      - 8003:8000
