#!/usr/bin/python3

lines=open('gallery.html.template').readlines()

html_doc=''.join(lines)

#for l in lines:
#	print(l,end='')

#for l in html:
#       print(l,end='')

#print(html_doc)

from bs4 import BeautifulSoup

soup = BeautifulSoup(html_doc, 'html.parser')

hrefs=soup.find_all('a')

#print(hrefs)

#print( hrefs[1]['href'] )


for el in soup.find_all('a'):
    oldsource=el['href']
    parsed = str('"{% static'+' '+'"' +oldsource+'"'+ ' '+'%}"')
    el['src']=parsed[1:-1]





print(soup.prettify())


#hrefs[1]['href']
